version: '3'

services:
  neo4j:
    image: neo4j:5.12.0
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/Infor2022

  python_app:
    build: 
      context: ./tvmatcher_scrapper
      dockerfile: Dockerfile-Scrapper
    environment:
      - OMDB_API_KEY=a1af39b  
      - PROVIDERS=netflix,amazon-prime-video,disney-plus,hbo-max,movistar-plus
    depends_on:
      - neo4j
      - springapp

  springapp:
    build: 
      context: ./Java-workspace/TVMatcher_neo4j
      dockerfile: Dockerfile-spring
    container_name: springapp
    ports:
      - "8080:8080" 
    environment:
      - spring.neo4j.uri=bolt://neo4j:7687
      - spring.neo4j.authentication.username=neo4j
      - spring.neo4j.authentication.password=Infor2022
      
    depends_on:
      - neo4j

  react_app:
    build:
      context: ./tvmatcher_react
      dockerfile: Dockerfile-react
    container_name: react_app
    ports:
      - "3000:3000"
