FROM alpine:3.16

RUN apk add --update py3-pip
WORKDIR /app/

COPY . /app/
COPY crontab /var/spool/cron/crontabs/root

RUN pip install -r requirements.txt

RUN chmod 0655 /app/scrapper.py

# Iniciar el cron después de ejecutar el scrapper
CMD python3 /app/scrapper.py && crond -l 2 -f